// chat-book-ui-admin/src/components/shared/request-state-panel.tsx
"use client";

import Link from "next/link";
import { AlertTriangle, CircleSlash, ShieldAlert } from "lucide-react";
import { cn } from "@/lib/utils";

type PanelTone = "neutral" | "danger" | "warning";

const panelToneMap: Record<PanelTone, { icon: typeof CircleSlash; className: string }> = {
  neutral: {
    icon: CircleSlash,
    className: "state-panel-neutral",
  },
  warning: {
    icon: AlertTriangle,
    className: "state-panel-warning",
  },
  danger: {
    icon: ShieldAlert,
    className: "state-panel-danger",
  },
};

export interface RequestStatePanelProps {
  title: string;
  description: string;
  tone?: PanelTone;
  actionLabel?: string;
  actionHref?: string;
}

export function RequestStatePanel({
  title,
  description,
  tone = "neutral",
  actionLabel,
  actionHref,
}: RequestStatePanelProps) {
  const toneConfig = panelToneMap[tone];
  const Icon = toneConfig.icon;

  return (
    <section className={cn("state-panel", toneConfig.className)}>
      <div className="state-panel-icon">
        <Icon className="h-5 w-5" />
      </div>
      <div className="space-y-2">
        <h3>{title}</h3>
        <p>{description}</p>
        {actionLabel && actionHref ? (
          <Link className="state-panel-link" href={actionHref}>
            {actionLabel}
          </Link>
        ) : null}
      </div>
    </section>
  );
}

// chat-book-ui-admin/src/components/shared/RequestStatePanel.vue
<template>
  <section :class="['state-panel', toneClass]">
    <div class="state-panel-icon">
      <span class="text-lg font-semibold">{{ toneSymbol }}</span>
    </div>
    <div class="space-y-2">
      <h3>{{ title }}</h3>
      <p>{{ description }}</p>
      <RouterLink v-if="actionLabel && actionHref" :to="actionHref" class="state-panel-link">
        {{ actionLabel }}
      </RouterLink>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { RouterLink } from "vue-router";

const props = withDefaults(
  defineProps<{
    title: string;
    description: string;
    tone?: "neutral" | "danger" | "warning";
    actionLabel?: string;
    actionHref?: string;
  }>(),
  {
    tone: "neutral",
  }
);

const toneClass = computed(() => {
  if (props.tone === "warning") return "state-panel-warning";
  if (props.tone === "danger") return "state-panel-danger";
  return "state-panel-neutral";
});

const toneSymbol = computed(() => {
  if (props.tone === "warning") return "!";
  if (props.tone === "danger") return "x";
  return "i";
});
</script>
